contracts/VotingMachines/GenesisProtocol.sol

GenesisProtocol - deposit reputation only for preboosting state proposal

---

.soliumrc.json
contracts/Reputation.sol
contracts/VotingMachines/GenesisProtocolCallbacksInterface.sol
contracts/test/AbsoluteVoteExecuteMock.sol
contracts/test/GenesisProtocolCallbacksMock.sol
package-lock.json
package.json
test/absolutevote.js
test/genesisprotocol.js
test/helpers.js
test/orderstatistictree.js
test/quorumvote.js
test/reputation.js
truffle.js

Support truffle V5 (web3 1.0)

---

contracts/VotingMachines/AbsoluteVote.sol
contracts/VotingMachines/GenesisProtocol.sol
contracts/VotingMachines/IntVoteInterface.sol
contracts/VotingMachines/QuorumVote.sol
package-lock.json
package.json
test/absolutevote.js
test/genesisprotocol.js
test/helpers.js
test/quorumvote.js

resolve #17 
bump version to 08

emit organization address  (instead of organizationId) at events.

---

contracts/VotingMachines/GenesisProtocol.sol
package.json

bump version to 09
resolve #20

make organizations public

---

.travis.yml
contracts/votingMachines/GenesisProtocol.sol
migrations/2_deploy_organization.js
package-lock.json
package.json
test/absolutevote.js
test/genesisprotocol.js
test/quorumvote.js
test/reputation.js
test/votingMachine.js

GenesisProtocol : add getter for DaoBounty

---

.soliumignore
.soliumrc.json
.travis.yml
README.md
contracts/Migrations.sol
contracts/Reputation.sol
contracts/libs/RealMath.sol
contracts/test/AbsoluteVoteExecuteMock.sol
contracts/test/Debug.sol
contracts/test/ERC827TokenMock.sol
contracts/test/GenesisProtocolCallbacksMock.sol
contracts/token/ERC827/ERC827.sol
contracts/token/ERC827/ERC827Token.sol
contracts/votingMachines/AbsoluteVote.sol
contracts/votingMachines/GenesisProtocol.sol
contracts/votingMachines/GenesisProtocolLogic.sol
contracts/votingMachines/IntVoteInterface.sol
contracts/votingMachines/ProposalExecuteInterface.sol
contracts/votingMachines/QuorumVote.sol
contracts/votingMachines/VotingMachineCallbacksInterface.sol
migrations/2_deploy_organization.js
package-lock.json
package.json
test/absolutevote.js
test/genesisprotocol.js
test/quorumvote.js
test/votingMachine.js
truffle.js

Remove voteWithSpecificAmount
Remove ownerVote
Remove cancelProposal
uint -> uint256
use solc v 0.5.2 https://github.com/ethereum/solidity/releases/tag/v0.5.2
use truffle 5.0 https://github.com/trufflesuite/truffle/releases/tag/v5.0.0
use openzeppling 2.1 https://github.com/OpenZeppelin/openzeppelin-solidity/releases
solium currently ignore GenesisProtocol.sol till it will support solc 0.5 . watch https://github.com/duaraghav8/Ethlint/issues/246

VotingMachine interface update

---

package-lock.json
package.json

"openzeppelin-solidity": "^2.1.0-rc.2"

---

contracts/test/AbsoluteVoteExecuteMock.sol
contracts/test/GenesisProtocolCallbacksMock.sol
contracts/token/ERC827/ERC827.sol
contracts/token/ERC827/ERC827Token.sol
contracts/votingMachines/AbsoluteVote.sol
contracts/votingMachines/GenesisProtocol.sol
contracts/votingMachines/GenesisProtocolLogic.sol
contracts/votingMachines/VotingMachineCallbacksInterface.sol
package-lock.json
package.json

use   "openzeppelin-solidity": "2.1.1"

---

contracts/libs/RealMath.sol
contracts/votingMachines/GenesisProtocolLogic.sol
package-lock.json
package.json

remove redundent realmath code

---

contracts/votingMachines/QuorumVote.sol

very low chances to happened ..but..lets do it,

fix quorum vote potential overflow

---

contracts/votingMachines/GenesisProtocol.sol
package-lock.json
package.json
test/genesisprotocol.js

GenesisProtocol : track valid signatures based on the nonce.

approveandstake: check stake nonce

---

.travis.yml
contracts/Migrations.sol
contracts/Reputation.sol
contracts/libs/RealMath.sol
contracts/test/AbsoluteVoteExecuteMock.sol
contracts/test/Debug.sol
contracts/test/ERC827TokenMock.sol
contracts/test/GenesisProtocolCallbacksMock.sol
contracts/token/ERC827/ERC827.sol
contracts/token/ERC827/ERC827Token.sol
contracts/votingMachines/AbsoluteVote.sol
contracts/votingMachines/GenesisProtocol.sol
contracts/votingMachines/GenesisProtocolLogic.sol
contracts/votingMachines/IntVoteInterface.sol
contracts/votingMachines/ProposalExecuteInterface.sol
contracts/votingMachines/QuorumVote.sol
contracts/votingMachines/VotingMachineCallbacksInterface.sol
package-lock.json
package.json
truffle.js

update solc and truffle versions 

---

contracts/libs/RealMath.sol
contracts/test/RealMathTester.sol
contracts/votingMachines/GenesisProtocolLogic.sol
package.json
test/genesisprotocol.js
test/realmath.js

add back 40 bit fraction part for accuracy.
Add realmath test

safer realmath

---

contracts/votingMachines/GenesisProtocolLogic.sol
package-lock.json
package.json
test/genesisprotocol.js

fix reputation flow.
fix potential underflow on redeem stakes
fix executeBoosted - to allows proposal in QuiteEndingPeriod state

fix reputation flow

---

contracts/votingMachines/GenesisProtocolLogic.sol
package-lock.json
package.json
test/genesisprotocol.js

A preBoosted proposal suppose to get back to Q if the preBoosted time has passed and the proposal confidence score is not greater than the dao threshold

fix handling preBoosted proposal 

---

package-lock.json
package.json

fix fsevents package vulnerability

---

contracts/Migrations.sol
contracts/Reputation.sol
contracts/libs/RealMath.sol
contracts/test/AbsoluteVoteExecuteMock.sol
contracts/test/Debug.sol
contracts/test/ERC827TokenMock.sol
contracts/test/GenesisProtocolCallbacksMock.sol
contracts/test/RealMathTester.sol
contracts/token/ERC827/ERC827.sol
contracts/token/ERC827/ERC827Token.sol
contracts/votingMachines/AbsoluteVote.sol
contracts/votingMachines/GenesisProtocol.sol
contracts/votingMachines/GenesisProtocolLogic.sol
contracts/votingMachines/IntVoteInterface.sol
contracts/votingMachines/ProposalExecuteInterface.sol
contracts/votingMachines/QuorumVote.sol
contracts/votingMachines/VotingMachineCallbacksInterface.sol
package-lock.json
package.json
truffle.js

bump Solc versions  to 0.5.13

---

contracts/Migrations.sol
contracts/Reputation.sol
contracts/libs/RealMath.sol
contracts/test/AbsoluteVoteExecuteMock.sol
contracts/test/Debug.sol
contracts/test/ERC827TokenMock.sol
contracts/test/GenesisProtocolCallbacksMock.sol
contracts/test/RealMathTester.sol
contracts/token/ERC827/ERC827.sol
contracts/token/ERC827/ERC827Token.sol
contracts/votingMachines/AbsoluteVote.sol
contracts/votingMachines/GenesisProtocol.sol
contracts/votingMachines/GenesisProtocolLogic.sol
contracts/votingMachines/IntVoteInterface.sol
contracts/votingMachines/ProposalExecuteInterface.sol
contracts/votingMachines/QuorumVote.sol
contracts/votingMachines/VotingMachineCallbacksInterface.sol
package-lock.json
package.json
truffle.js

solc 0.5.17

---

.travis.yml
package-lock.json
package.json
release-experimental.sh

shift to master-2

---

contracts/Reputation.sol
package-lock.json
package.json
test/reputation.js

Fix rep decimals
